name: Build Pull Request

on:
  pull_request:
    branches: [ master-ame ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pull-request-build
        path: build/libs/
